application: bihyaku
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /bijin/(.+)
  static_files: index.html
  upload: index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(.*)
  static_files: \1
  upload: (.*)
