application: bihyaku
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /bijin/(.+)
  static_files: index.html
  upload: index.html

# - url: /bijin-zoroe/
#   static_files: bijin-zoroe/index.html
#   upload: bijin-zoroe/index.html

# - url: /bijin-zoroe/(.*)
#   static_files: bijin-zoroe/\1
#   upload: bijin-zoroe/(.*)

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(.*)
  static_files: \1
  upload: (.*)
